name: Docs

on:
  push:
    paths:
      - "docs/**"

jobs:
  file_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Local Repository
        uses: actions/checkout@master
      - name: File Sync
        uses: kbrashears5/github-action-file-sync@v2.0.0
        with:
          REPOSITORIES: |
            discordeno/guide@main
          FILES: |
            docs/=.
          TOKEN: ${{ secrets.DOCS_SYNC }}
