name: Release

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno: ["v1.x"]
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@main
        with:
          deno-version: ${{ matrix.deno }}
      - name: Get tag version
        id: get_tag_version
        run: |
          version=`cat util/constants.ts | grep 'export const DISCORDENO_VERSION' | awk -F'= ' '{print $2}' | tr -d '"|;'`
          echo "DISCORDENO_VERSION=$version" >> $GITHUB_ENV
      - name: Create tag
        run: echo ${{ env.MY_VARIABLE }}

