name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno: ["v1.x", "nightly"]
    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno }}
      - name: Cache dependencies
        run: deno cache --no-check mod.ts
      - name: Run test script
        if: ${{ github.event.label.name == 'run-tests' }}
        run: deno test -A --no-check
    env:
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
